# This is the name of our workflow.
# Github will show it on its Website UI
name: algolia
# This configures our workflow to be triggered
# only when we push to the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'

# Here is where we define our jobs.
# Which means the tasks we want Github to execute
jobs:
  build:
    name: deploy
    # Here we specify in whith OS we want it to run
    runs-on: ubuntu-latest
    # Now we define which actions will take place.
    # One after another
    steps:
      # This is the first action. It will make sure that we have
      # all the necessary files from our repo, including our custom actions
      # This action here is actually from a remote repo available from Githup itself
      - name: 🛎 Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y --no-install-recommends bats build-essential ca-certificates curl make shellcheck libgsl-dev libffi-dev
          sudo gem install bundler:2.2.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get cached gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setting up dependencies
        run: |
          bundle install
      - name: 🔨 Build site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --trace --verbose --lsi
      - name: Algolia Jekyll Action
        uses: dieghernan/algolia-jekyll-action@v1
        with:
          APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'
