name: Weekly Link Check

on:
  schedule:
    # Kører hver mandag kl. 08:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch: # Gør det muligt at starte workflowet manuelt under "Actions" fanen

env:
  RUBY_VERSION: "3.3.2"
  BUNDLER_VERSION: "2.5.11"

jobs:
  check-links:
    name: Check All External Links
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: ⚡️ Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential ca-certificates curl libgsl-dev libffi-dev liblapacke-dev libopenblas-dev
          sudo gem install bundler:${{ env.BUNDLER_VERSION }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: 🔨 Build site for testing
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: 📉 Check HTML (Internal & External)
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          arguments: |
            --only-4xx
            --ignore-status-codes "400,401,403,409,429,999"
            --ignore-empty-alt
            --allow-hash-href
            --no-enforce-https
            --ignore-urls "/bjsm.bmj.com/, /mademistakes.com/, /www.t-nation.com/, /pubmed.ncbi.nlm.nih.gov/, /doi.org/"